about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

admin.site.site_header = "Sabin Admin page"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to sabin Admin page"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('project/', views.project, name='project'),
    path('award/', views.award, name='award'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models
# Create your models here.


class About(models.Model):
    title = "About me"
    discription = models.TextField()
    image = models.ImageField(upload_to='portfolio/image/')

    def __str__(self):
        return self.title

blog/models.py
from django.db import models
# Create your blog models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    discription = models.TextField()
    image = models.ImageField(upload_to='portfolio/image/')
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/image/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title


class Award(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/image/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .models import About
# Create your views here.


def about(request):
    abouts = About.objects.all()
    return render(request, 'about/about.html', {'abouts': abouts})

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from .models import Blog
# Create your  blog views here.


def all_blog(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blog.html', {'blogs': blogs})


def detail(request, blog_id):
    # pk is primary key, BLog hold title discription and more and pk gives blog_id
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .models import Project, Award
# Create your views here.


def home(request):
    return render(request, "portfolio/home.html")


def project(request):
    global projects
    projects = Project.objects.all()
    context = {
        'projects': projects,
    }
    return render(request, 'portfolio/projects.html', context)


def award(request):
    global projects
    awards = Award.objects.all()
    context = {
        'awards': awards,
    }
    return render(request, 'portfolio/award.html', context)

about/templates/about/about.html
{% extends 'about/base.html' %} {% block content %}
<br />
<br />
<br />
<br />
<br />
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">
      Sabin <colour style="color: rgb(65, 170, 153);"> Adhikari</colour>
    </h1>
  </div>
</div>
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <p id="info" class="font-weight-light">
      New road Narayangadh-Chitwan,Nepal. Contact:+9779821266270, Mail:<colour
        id="mail"
        style="color: #ce01f7;"
        >sabinadhikari494@gmail.com</colour
      >
    </p>
  </div>
</div>
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <div class="social-buttons">
      <a href="https://www.facebook.com/sabinadhikari494"
        ><i class="fab fa-facebook"></i
      ></a>
      <a href="https://www.instagram.com/adhikarii.sabin/"
        ><i class="fab fa-instagram"></i
      ></a>
      <a href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>
      <a href="https://www.linkedin.com/in/sabin-adhikari-5b9b821b0/"
        ><i class="fab fa-linkedin-in"></i
      ></a>
    </div>
  </div>
</div>
<br />
<br />
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">
      <i class="fa fa-arrow-circle-down"></i>
    </h1>
  </div>
</div>
<br />
{% for about in abouts %}
<div class="row">
  <div class="col-md-4">
    <img
      src="{{ about.image.url }}"
      class="img-thumbnail border-dark"
      data-size="1920x1080"
    />
  </div>
  <div class="col-md-8">
    <p style="color: white;" id="aboutme">{{ about.discription }}</p>
  </div>
</div>
{% endfor %} {% endblock %}

about/templates/about/base.html
{% load static %}
<!-- about base.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'about/style.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />

    <link rel="icon" type="image/png" href="{% static 'about/Logo.png' %}" />
    <title>About Sabin</title>
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-md navbar-dark"
      style="background: transparent;"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/me.jpg' %}"
            width="50"
            height="50"
            class="d-inline-block align-top"
            id="img"
            alt="Logo"
            style="border-radius: 50%;"
          />
        </a>
        <button
          class="navbar-toggler white"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}"
                ><i class="fas fa-home"></i>Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about' %}"
                ><i class="fa fa-user"></i>About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project' %}"
                ><i class="fa fa-cogs"></i>Projects</a
              >
            </li>
            <li>
              <a class="nav-link" href="{% url 'blog:all_blog' %}"
                ><i class="fas fa-blog"></i>Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'award' %}"
                ><i class="fa fa-trophy" aria-hidden="true"></i>Awards</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" id="content">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/blog/all_blog.html
<title>My Blogs List</title>
{% extends 'blog/base.html' %} {% block content %}
<center>
  <h1 style="color: white;">Welcome to My Blog Gateway</h1>
  <h2 style="color: white;">
    I have written {{blogs.count}} blog{{blogs.count|pluralize}}
  </h2>
</center>
<br />
{% for blog in blogs %}
<h2 style="color: white;">
  <a href="{% url 'blog:detail' blog.id %}" style="color: rgb(50, 139, 109);"
    >{{ blog.title }}</a
  >
</h2>
<h5 style="color: white;">{{ blog.date|date:'M d Y'}}</h5>
<p style="color: white;">{{ blog.discription|striptags|truncatechars:100 }}</p>
{% endfor %} {% endblock %}

blog/templates/blog/base.html
{% load static %}
<!-- blog base.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'blog/style.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/png"
      href="{% static 'portfolio/Logo.png' %}"
    />
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-md navbar-dark"
      style="background: transparent;"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/me.jpg' %}"
            width="50"
            height="50"
            class="d-inline-block align-top"
            alt="Logo"
            style="border-radius: 50%;"
          />
        </a>
        <button
          class="navbar-toggler white"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}"
                ><i class="fas fa-home"></i>Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about' %}"
                ><i class="fa fa-user"></i>About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project' %}"
                ><i class="fa fa-cogs"></i>Projects</a
              >
            </li>
            <li>
              <a class="nav-link" href="{% url 'blog:all_blog' %}"
                ><i class="fas fa-blog"></i>Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'award' %}"
                ><i class="fa fa-trophy" aria-hidden="true"></i>Awards</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %} {% block content %}<br />
<title>{{ blog.title }}</title>
<h1 style="color: white;">{{ blog.title }}</h1>
<h2 style="color: white;">{{ blog.date|date:'M d Y' }}</h2>
<img src="{{ blog.image.url }}" class="img-fluid" data-size="1920x1080" /><br />
<pree style="color: white;">{{ blog.discription|striptags|linebreaks }}</pree>
{% endblock %}

portfolio/templates/portfolio/award.html
{% extends "portfolio/base_award.html" %}{% load static %}{% block content %}
<center>
  <h2 style="color: white;">
    My {{awards.count}} Award{{ awards.count|pluralize}}
  </h2>
</center>
<hr />
<div class="row">
  {% for award in awards %}
  <div class="col-lg-4 col-md-6">
    {% if award.url %}
    <a href="{{ award.url }}">
      <img
        src="{{ award.image.url }}"
        class="img-thumbnail"
        style="border-radius: 20px;"
      />
    </a>
    {% else %}
    <img
      src="{{ award.image.url }}"
      class="img-thumbnail"
      style="border-radius: 20px;"
    />
    {% endif %}
    <h3 style="color: white;">{{ award.title }}</h3>
    <p style="color: white;">{{ award.discription }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/png"
      href="{% static 'portfolio/Logo.png' %}"
    />

    <title>Sabin</title>
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-md navbar-dark"
      style="background: transparent;"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/me.jpg' %}"
            width="150"
            height="150"
            class="d-inline-block align-top"
            alt="Logo"
            style="border-radius: 50%;"
          />
        </a>
        <button
          class="navbar-toggler white"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}"
                ><i class="fas fa-home"></i>Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about' %}"
                ><i class="fa fa-user" aria-hidden="true"></i>About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project' %}"
                ><i class="fa fa-cogs" aria-hidden="true"></i>Projects</a
              >
            </li>
            <li>
              <a class="nav-link" href="{% url 'blog:all_blog' %}"
                ><i class="fas fa-blog"></i>Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'award' %}"
                ><i class="fa fa-trophy" aria-hidden="true"></i>Awards</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

portfolio/templates/portfolio/base_award.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'award/style.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/png"
      href="{% static 'portfolio/Logo.png' %}"
    />

    <title>My Awards</title>
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-md navbar-dark"
      style="background: transparent;"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/me.jpg' %}"
            width="50"
            height="50"
            class="d-inline-block align-top"
            alt="Logo"
            style="border-radius: 50%;"
          />
        </a>
        <button
          class="navbar-toggler white"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}"
                ><i class="fas fa-home"></i>Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about' %}"
                ><i class="fa fa-user" aria-hidden="true"></i>About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project' %}"
                ><i class="fa fa-cogs" aria-hidden="true"></i>Projects</a
              >
            </li>
            <li>
              <a class="nav-link" href="{% url 'blog:all_blog' %}"
                ><i class="fas fa-blog"></i>Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'award' %}"
                ><i class="fa fa-trophy"></i>Awards</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

portfolio/templates/portfolio/base_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'project/style.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />
    <title>My projects</title>
    <link
      rel="icon"
      type="image/png"
      href="{% static 'portfolio/Logo.png' %}"
    />

    <title>Sabin</title>
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-md navbar-dark"
      style="background: transparent;"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/me.jpg' %}"
            width="50"
            height="50"
            class="d-inline-block align-top"
            alt="Logo"
            style="border-radius: 50%;"
          />
        </a>
        <button
          class="navbar-toggler white"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}"
                ><i class="fas fa-home"></i>Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about' %}"
                ><i class="fa fa-user" aria-hidden="true"></i>About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project' %}"
                ><i class="fa fa-cogs" aria-hidden="true"></i>Projects</a
              >
            </li>
            <li>
              <a class="nav-link" href="{% url 'blog:all_blog' %}"
                ><i class="fas fa-blog"></i>Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'award' %}"
                ><i class="fa fa-trophy" aria-hidden="true"></i>Awards</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>